#!/bin/sh

# Compile
gcc -g -o test  test.c  						\
				clientService.c  				\
				../login/login.c  				\
				../../lib/json/json.c  			\
				../../lib/frame/frame.c  		\
				../../lib/fileproc/fileproc.c  	\
				../../lib/logfile/logfile.c 	\
				-ljansson

# Run
./test 1211912340432134
