#!/bin/sh

# Compile
gcc -o test test.c frame.c

# Testbench of encoding
# ./test encode 6 0 3 123
# ./test encode 6 1 5 1234560654321

# Testbench of decoding
./test decode 1 2 6 3 3 1 2 3 4 4 1 2 6 3 3 1 2 3 3 4 
