#! /bin/sh
# Compile
gcc -g -o embedded-shell	embedded-shell.c  						\
							clientService/clientService.c  			\
							login/login.c  							\
							../lib/json/json.c  					\
							../lib/frame/frame.c  					\
							../lib/fileproc/fileproc.c  			\
							../lib/logfile/logfile.c 				\
							../lib/communication/communication.c 	\
							-ljansson

# Run
./embedded-shell 1 3 123 234	# {addr, fnc, usr, pass}

# ./run-embedded-shell