#! /bin/sh
# Compile
rm embedded-shell
gcc -g -o embedded-shell	embedded-shell.c  						\
							clientService/clientService.c  			\
							login/login.c  							\
							../lib/json/json.c  					\
							../lib/frame/frame.c  					\
							../lib/fileproc/fileproc.c  			\
							../lib/logfile/logfile.c 				\
							../lib/communication/communication.c 	\
							-ljansson

# Run
clear
./embedded-shell

# ./run-embedded-shell